CSL1	MAR=SP=SP-1;RD		// PUTS THE SECOND ENTRY OF THE STACK IN MAR
CSL2 				// WAIT FOR THE READ PROCESS TO FINISH
CSL3	H=OPC=TOS		// TOS IS ASSIGNED TO OPC AND H
CSL4	H=H+OPC			// THE SHIFT OCCURS BY ADDING H TO H
CLS5 	TOP=H			// ASSIGN H BACK TO TOP OF THE STACK
